### ISSUE TITLE
Create a  template issue for logo opt in/opt out

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat2.github.io#29]
@bybai If you want to ask customer to opt-in or opt-out, let's create a template for logos 

https://help.github.com/en/articles/creating-issue-templates-for-your-repository

Here we can ask the customer to provide us some information that we want...  we can have a discussion here ... 

* Opt In  / Opt out
* Maybe provide us with a image file or a URL to their corporate logos?

**Comment by bybai** [comment]
Hi @whowutwut,

I think the Opt in/Opt out templates should be simple enough, so that customer can easily open a issue here.  Another problem here, if customer does not have github account and they just reply our mail, how can we keep the mail content?  Do we open an issue in github, and attach the mail?   
 
1. Opt In template:
Title:  Opt in xCAT home page customer list
Content:
### Welcome to xCAT
### Organization Name : [                                  ]

### Paste organization logo or logo URL:
[                                  ]

### If you are willing to share success stories of xCAT within 100 words:
[                                  ]

2. Opt out template:
Title: Opt out xCAT home page customer list
Content:
### Welcome to xCAT
### Organization Name : [                                  ]
### Opt out reason: 
[                                   ]
